name: Secrel Public Interface

on:
  workflow_call:
    inputs:
      config-file:
        required: true
        type: string
      images:
        required: true
        type: string

jobs:
  call-secrel:
    runs-on: ubuntu-latest
    steps:
      - name: Run Secrel
        run: |
          curl -s -X POST -H "Authorization: token $GITHUB_TOKEN" -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/department-of-veterans-affairs/lighthouse-secrel-test-fixtures-2/actions/workflows/$WORKFLOW_FILE/dispatches -d "'{"ref": "v4", "inputs": $INPUTS }'"