name: Secrel Public Interface

on:
  workflow_call:
    inputs:
      config-file:
        required: true
        type: string
      images:
        required: true
        type: string
    secrets:
      SECREL_FGAT:
        required: true

jobs:
  call-secrel:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Secrel Code
        uses: actions/checkout@v3
        with:
          repository: department-of-veterans-affairs/lighthouse-tornado-secrel-pipeline
          ref: main
          token: ${{ secrets.SECREL_FGAT }}
      - name: Run Secrel
        uses: ./.github/workflows/pipeline.yml
        with:
          config-file: ${{ inputs.config-file }}
          images: ${{ inputs.images }}
        secrets: inherit