name: Secrel Public Interface

on:
  workflow_call:
    inputs:
      config-file:
        required: true
        type: string
      images:
        required: true
        type: string

jobs:
  call-secrel:
    runs-on: ubuntu-latest
    steps:
      - name: Run Secrel
        env:
          SECREL_FGAT: ${{ secrets.SECREL_FGAT }}
          CONFIG: ${{ github.event.inputs.config-file }}
          IMAGES: ${{ github.event.inputs.images }}
        run: |
          curl -s -X POST -H "Authorization: token $SECREL_FGAT" -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/department-of-veterans-affairs/lighthouse-tornado-secrel-pipeline/workflows/pipeline.yml/dispatches -d "'{"ref": "v4", "inputs": {"config-file": $CONFIG, "images": $IMAGES} }'"