name: Secrel Public Interface

on:
  workflow_call:
    inputs:
      config-file:
        required: true
        type: string
      images:
        required: true
        type: string
    secrets:
      SECREL_FGAT:
        required: true

jobs:
  call-secrel:
    runs-on: ubuntu-latest
    steps:
      - name: Run Secrel
        env:
          SECREL_FGAT: ${{ secrets.SECREL_FGAT }}
          CONFIG: ${{ inputs.config-file }}
          IMAGES: ${{ inputs.images }}
        run: |
          echo "CONFIG::"
          echo $CONFIG

          echo "\nIMAGES::"
          echo $IMAGES
          curl -s -H "Authorization: token $SECREL_FGAT" \
            -H "Accept: application/vnd.github.v3+json" \
            --request POST \
            "https://api.github.com/repos/department-of-veterans-affairs/lighthouse-tornado-secrel-pipeline/actions/workflows/pipeline.yml/dispatches" \
            -d "'{\"ref\": \"v4\", \"inputs\": {\"config-file\": \"$CONFIG\", \"images\": \"$IMAGES\"} }'"